version: '3'
services:
  layout:
    build: .
    ports: [ "8080:8080" ]
  common:
    build: fragments/common
    environment:
      PORT: 3009
    ports: ["3009:3009" ]
  app1:
    build: fragments/app1
    environment:
      PORT: 3011
    ports: ["3011:3011"]
  app1_1:
    build: fragments/app1_1
    environment:
      PORT: 3022
    ports: ["3022:3022"]
