version: '3'
services:
  layout:
    build: .
    ports: [ 8080 ]
    network_mode: "host"
  common:
    build: fragments/common
    environment:
      PORT: 3009
    ports: ["3009:3009" ]
    network_mode: "host"
  app1:
    build: fragments/app1
    environment:
      PORT: 3011
    ports: ["3011:3011"]
  app1_1:
    build: fragments/app1_1
    environment:
      PORT: 3022
    ports: ["302:3022"]
    network_mode: "host"
